spring.application.name=LBTLMS

server.port=${SERVER_PORT:8081}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true


#(300000ms = 5 mins)
author.cache.refresh-interval-ms=300000
book.cache.refresh-interval-ms=300000
member.cache.refresh-interval-ms=300000